spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          demo-client:
            provider: demo-provider
            client-id: demo-client
            client-secret: client-secret
            authorization-grant-type: client_credentials
            scope: read
        provider:
          demo-provider:
            token-uri: http://localhost:9000/oauth2/token